# docker-compose configuration for DEVELOPMENT.

# Note that we are using docker-sync to speed up file syncing of Docker for Mac.
# ref: https://github.com/EugenMayer/docker-sync
# You can use executables in the `dk` directory to run this docker-compose containers easily.

version: '3'

services:
  db:
    image: postgres:10.4
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build: &server_build
      context: .
      dockerfile: Dockerfile-server
    volumes: &server_volumes
      - root-sync:/server:nocopy
      - bundle:/usr/local/bundle
    environment: &server_environment
      - WRACKET_DB_HOST=db
      - WRACKET_DB_USER=postgres
    depends_on:
      - db
      - front
    ports:
      - '3000:3000'
    command: bin/rails s -b '0.0.0.0'

  spring:
    build: *server_build
    volumes: *server_volumes
    environment: *server_environment
    depends_on:
      - db
    tty: false
    stdin_open: false
    command: bin/spring server

  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    volumes:
      - root-sync:/front:nocopy
      - node_modules:/front/node_modules
    environment:
      - ASSET_PORT=3001
    ports:
      - '3001:3001'
    command: yarn start

volumes:
  root-sync:
    external: true
  postgres:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
