# docker-compose configuration for DEVELOPMENT.

# First, we are using docker-sync to speed up file syncing of Docker for Mac.
# https://github.com/EugenMayer/docker-sync
# So do not forget to run `docker-sync start` before starting development.
#
# To run the application:
#
#   docker-compose run --rm --service-ports server
#
# Using `docker-compose run` instead of `docker-compose up` allows us to
# use `binding.pry` easily as if we run the server on a host machine.
#
# To run rails commands such as `console` or `test`:
#
#   docker-compose exec spring bin/rails c
#
# Since the `spring` container runs the spring server,
# it speeds up those rails commands launching.

version: '3'

services:
  db:
    image: postgres:10.4
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build: &server_build
      context: .
      dockerfile: Dockerfile.server
    volumes: &server_volumes
      - root-sync:/server:nocopy
      - bundle:/usr/local/bundle
    environment: &server_environment
      - WRACKET_DB_HOST=db
      - WRACKET_DB_USER=postgres
    depends_on:
      - db
      - front
      - spring
    ports:
      - '3000:3000'
    command: bin/rails s -b '0.0.0.0'

  spring:
    build: *server_build
    volumes: *server_volumes
    environment: *server_environment
    depends_on:
      - db
      - front
    tty: false
    stdin_open: false
    command: bin/spring server

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - root-sync:/front:nocopy
      - node_modules:/front/node_modules
    environment:
      - ASSET_PORT=3001
    ports:
      - '3001:3001'
    command: yarn start

volumes:
  root-sync:
    external: true
  postgres:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
