# Since the Git binary Yum provides is too old,
# we should build and install Git from the source.
# ref: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

- name: 'Git: install dependencies'
  yum:
    name: '{{item}}'
  with_items:
    - gcc
    - make
    - autoconf
    - openssl-devel
    - perl-ExtUtils-MakeMaker

- name: 'Git: download source'
  shell: 'curl -L {{git_source_url}} | tar zx -C /tmp'
  args:
    warn: False

- name: 'Git: build'
  command: '{{item}}'
  args:
    chdir: '/tmp/git-{{git_version}}'
  with_items:
    - make configure
    - ./configure --prefix=/usr
    - make all
    - make install
