- name: add group for app
  group:
    name: '{{app_group}}'

- name: add user for app
  user:
    name: '{{app_user}}'
    password: '{{ user_password | password_hash("sha512") }}'
    shell: /bin/bash
    groups:
      - '{{app_group}}'
      - wheel
    update_password: on_create
    append: yes

- name: install epel-release
  yum:
    update_cache: yes
    name: epel-release
  tags: ['yum']

- name: check if git exists
  command: which git
  register: which_git
  ignore_errors: true
  tags: ['git']

- import_tasks: _git.yml
  when: which_git.rc != 0
  tags: ['git']
