# Configure Let's Encrypt for Nginx.
# https://letsencrypt.org/
# https://certbot.eff.org/lets-encrypt/centosrhel7-nginx
#
# Note that this role does not modify Nginx configuration at all.

# XXX:
# If you run this role as a step of 'setup.yml' playbook for the first time,
# currently the certificate installation will fail.
# This is because the Nginx configuration file already contains
# settings for HTTPS that loads certificates from the 'letsencrypt' directory.
# But since these files does not exist yet, `nginx -t` fails and 'certbot' command
# fails too.
# In addition, a Nginx process still remains after certificates installation.
# I fixed these problems manually at that time. Next time, I think
# we should try to use certbot as a standalone mode.
# In that case certbot does not use Nginx.

- name: install certbot for Nginx
  yum:
    name: python2-certbot-nginx

- name: get stat of domain archive directory
  stat:
    path: '/etc/letsencrypt/archive/{{app_domain}}'
  register: cert_archive_dir

- name: install certificate for app
  command: >
    certbot --nginx certonly
      -n
      -d '{{app_domain}}'
      -m '{{admin_email}}'
      --agree-tos
  when: not cert_archive_dir.stat.exists

- name: define certificate renewal service
  template:
    src: templates/cert-renew.service
    dest: '{{systemd_unit_dir}}/cert-renew.service'
  register: renewal_service

- name: define certificate renewal timer
  template:
    src: templates/cert-renew.timer
    dest: '{{systemd_unit_dir}}/cert-renew.timer'
  register: renewal_timer

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
  when: renewal_service.changed or renewal_timer.changed

- name: enable certificate renewal timer
  systemd:
    name: cert-renew.timer
    enabled: yes
    state: started
