# Configure Let's Encrypt.
#
# https://letsencrypt.org/
#
# Though we use Nginx as a web server,
# we choose to use Certbot without Nginx integration for simplicity.
# https://certbot.eff.org/lets-encrypt/centosrhel7-other

- name: install certbot for Nginx
  yum:
    name: certbot

- name: get stat of domain archive directory
  stat:
    path: '/etc/letsencrypt/archive/{{app_domain}}'
  register: cert_archive_dir

- name: install certificate for app
  # https://certbot.eff.org/docs/using.html#webroot
  command: >
    certbot certonly
      -n
      --webroot
      -w '{{nginx_web_root}}'
      -d '{{app_domain}}'
      -m '{{admin_email}}'
      --agree-tos
  when: not cert_archive_dir.stat.exists

- name: define certificate renewal service
  template:
    src: templates/cert-renew.service
    dest: '{{systemd_unit_dir}}/cert-renew.service'
  register: renewal_service

- name: define certificate renewal timer
  template:
    src: templates/cert-renew.timer
    dest: '{{systemd_unit_dir}}/cert-renew.timer'
  register: renewal_timer

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
  when: renewal_service.changed or renewal_timer.changed

- name: enable certificate renewal timer
  systemd:
    name: cert-renew.timer
    enabled: yes
    state: started
