# https://cloud.google.com/logging/docs/agent/installation

- name: get stat of root directory
  stat:
    path: '{{stackdriver_root}}'
  register: root_dir

- name: install agent if necessary
  block:
  - name: download installer script
    get_url:
      url: '{{stackdriver_installer_url}}'
      dest: /tmp/install-logging-agent.sh
      mode: '0644'

  - name: install agent
    command: bash /tmp/install-logging-agent.sh
    become: yes

  when: not root_dir.stat.exists

- name: put config files for Rails log
  template:
    src: 'templates/wracket.conf'
    dest: '{{stackdriver_root}}/config.d/wracket.conf'

# Currently we need to use init.d instead of systemd...
- name: restart agent
  service:
    name: google-fluentd
    enabled: yes
    state: restarted
