default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV["WRACKET_DB_HOST"] %>
  username: <%= ENV["WRACKET_DB_USER"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wracket_development

test:
  <<: *default
  database: wracket_test

production:
  <<: *default
  database: wracket_production
  username: wracket
  password: <%= ENV['WRACKET_DB_PASSWORD'] %>
