- name: install Nginx
  yum:
    update_cache: yes
    name: nginx
  tags: ['yum']

- name: prepare sites-available directory
  file:
    path: /etc/nginx/sites-available
    state: directory

- name: prepare sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory

- name: get stat of default nginx.conf backup
  stat:
    path: /etc/nginx/nginx.conf.default
  register: nginx_conf_backup

- name: back up default nginx.conf
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.default
  when: not nginx_conf_backup.stat.exists

- name: put nginx.conf
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: put conf for wracket
  template:
    src: templates/nginx-wracket.conf
    dest: /etc/nginx/sites-available/wracket.conf
  vars:
    backend_port: '{{ports["blue"]}}'

- name: put conf symlink
  file:
    src: /etc/nginx/sites-available/wracket.conf
    dest: /etc/nginx/sites-enabled/wracket.conf
    state: link

- name: enable httpd_can_network_connect of SELinux
  command: setsebool httpd_can_network_connect 1
