- import_tasks: _app_conf.yml
  vars:
    backend_port: '{{port}}'

- name: put nginx.conf
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: reload nginx
  systemd:
    name: nginx
    state: restarted
