- name: '{{color}}: create directory'
  file:
    dest: '{{workdir}}/{{color}}'
    state: directory
    owner: '{{app_user}}'
    group: '{{app_group}}'
    mode: '700'

- name: '{{color}}: create id file'
  copy:
    content: '{{color}}'
    dest: '{{workdir}}/{{color}}/id'
    owner: '{{app_user}}'
    group: '{{app_group}}'

- name: '{{color}}: add executable'
  template:
    src: templates/service
    dest: '{{workdir}}/{{color}}/service'
    mode: '0755'
    owner: '{{app_user}}'
    group: '{{app_group}}'

- name: '{{color}}: define systemd unit'
  template:
    src: templates/wracket.service
    dest: '{{systemd_unit_dir}}/wracket-{{color}}.service'
    owner: root
    group: root
    mode: '0644'

- name: '{{color}}: enable systemd daemon'
  systemd:
    name: 'wracket-{{color}}'
    enabled: yes

# Add 'public_content_t' type for files in the public directory
# to allow Nginx to serve static files inside it.
- name: '{{color}}: define SELinux context for public directory'
  command: >
    semanage fcontext -a -t public_content_t --
    "{{workdir}}/{{color}}/app/public(/.*)?"
